### PR TITLE
updated from euhan

### PR DESCRIPTION
**Pull request by euhansarkar**
**don't merge these codes**

### CODE REVIEW

**Review by farukphero — CHANGES_REQUESTED** [review]
Please change <a> tag to <Link>

**Comment by euhansarkar** [comment]
changes done

**Review by farukphero — APPROVED** [review]

**Comment by farukphero** [comment]
thanks

**Review by farukphero — APPROVED** [review]

**Comment by euhansarkar** [comment]
is there any conflict in code ?

**Review by farukphero — APPROVED** [review]

**Review by farukphero — APPROVED** [review]

**Review by farukphero — APPROVED** [review]

**Pull request merged**
